version: 2
jobs:
  build:
    docker:
      - image: node:7.9.0

    working_directory: ~/tenbyten

    steps:
      - checkout

      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"

      - run:
          name: ESLint
          command: node_modules/.bin/eslint src

      # Deploy to Github Pages
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy
            fi
