version: 2
jobs:
  build:
    docker:
      - image: node:7.9.0

    working_directory: ~/tenbyten

    steps:
      - checkout

      - restore_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "/home/ubuntu/.yarn-cache"

      - run:
          name: ESLint
          command: node_modules/.bin/eslint src

      - add_ssh_keys:
          fingerprints:
            - "9f:18:e6:99:0a:23:5c:c1:06:ce:75:c5:d0:51:19:41"

      # Deploy to Github Pages
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config user.email "automation@elem.us"
              git config user.name "Automated Deploy"
              npm run deploy
            fi
